# Generated by Django 2.1 on 2018-08-17 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schooler', '0002_auto_20180816_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
