# Generated by Django 2.1 on 2018-08-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooler', '0005_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
